-- ============================================================
-- ui-ux-redesign · 数据库脚本声明（零 DDL）
-- ============================================================
-- 适配口径：VeloxMark 为 Electron 桌面应用，无 MySQL、无后端服务。
-- 本需求「数据库」= 渲染进程 localStorage 双键 schema
--   veloxmark.preferences / veloxmark.session
-- 真源：src/renderer/src/preferences/store.ts
--       （TypeScript 接口 + 逐字段白名单 sanitizer）
--
-- 变更清单（详见 ../db/db.md）：
--   1. SessionState 新增平铺字段 quoteFolds: Record<filePath, string[]>
--      —— additive、低风险、无迁移、无历史数据兼容需求
--
-- 本文件不含任何可执行 SQL 语句（无 CREATE/ALTER/DROP）。
-- 存在此处仅为交付物门禁（design/sql/*.sql）的显式零变更声明；
-- MySQL 设计规范（sql-design-spec：biz_key/软删除/必备字段）对
-- localStorage JSON 存储整体不适用，属适配性豁免而非字段级偏差。
-- ============================================================
