/**
 * P14 native-menu strings (darwin application menu) — pure data leaf module.
 *
 * Task 3.17: moved verbatim from electron/menu/darwin.ts so the 0.2 i18n
 * alignment test can import and guard this third dictionary (key sets equal
 * across zh/en, no duplicate key literals, {placeholder} parity). Values are
 * byte-identical to the pre-move inline copy — menu labels must not drift.
 *
 * Entries are one-per-line so the key-literal source scan (guards against
 * silent last-wins duplicate keys in object literals) applies here too.
 */
export const NATIVE_MENU_STRINGS: Record<'zh' | 'en', Record<string, string>> = {
  en: {
    app: 'VeloxMark',
    services: 'Services',
    hide: 'Hide VeloxMark',
    hideOthers: 'Hide Others',
    unhide: 'Show All',
    quit: 'Quit VeloxMark',
    preferences: 'Preferences…',
    file: 'File',
    newFile: 'New',
    openFile: 'Open…',
    openFolder: 'Open Folder…',
    quickOpen: 'Quick Open…',
    openRecent: 'Open Recent',
    noRecent: 'No Recent Files',
    clearMenu: 'Clear Menu',
    save: 'Save',
    saveAs: 'Save As…',
    export: 'Export',
    pdf: 'PDF…',
    html: 'HTML…',
    close: 'Close',
    closeTab: 'Close Tab',
    reopenClosedTab: 'Reopen Closed Tab',
    nextTab: 'Next Tab',
    edit: 'Edit',
    cut: 'Cut',
    copy: 'Copy',
    paste: 'Paste',
    pasteMatch: 'Paste and Match Style',
    del: 'Delete',
    selectAll: 'Select All',
    copyRichText: 'Copy as Rich Text',
    copyAsHtml: 'Copy as HTML',
    exportSelectionHtml: 'Export Selection as HTML…',
    insertTable: 'Insert Table…',
    convertToTable: 'Convert Selection to Table…',
    formatDocument: 'Format Document',
    format: 'Format',
    bold: 'Bold',
    italic: 'Italic',
    inlineCode: 'Inline Code',
    strikethrough: 'Strikethrough',
    highlight: 'Highlight',
    view: 'View',
    toggleOutline: 'Toggle Outline',
    globalSearch: 'Search in Folder…',
    focusMode: 'Focus Mode',
    typewriterMode: 'Typewriter Mode',
    sourceMode: 'Source Mode',
    typingAssists: 'Typing Assists',
    wrapBareUrls: 'Wrap Bare URLs on Paste',
    pasteHtmlMd: 'Convert HTML on Paste',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    zoomReset: 'Reset Zoom',
    devTools: 'Toggle Developer Tools',
    toggleTheme: 'Toggle Theme',
    insert: 'Insert',
    insertMermaidDiagram: 'Mermaid Diagram…',
    insertCallout: 'Insert Callout…',
    window: 'Window',
    minimize: 'Minimize',
    zoom: 'Zoom',
    fullscreen: 'Enter Full Screen',
    front: 'Bring All to Front',
    help: 'Help',
    showHelp: 'Markdown Syntax Reference',
    // ---- menu-tree §3 semantic group names (BE-02, menu:native-parity) ----
    // Key names mirror the renderer i18n menu.grp.* keys (FE-01 same inventory,
    // third dictionary maintained independently but semantically aligned).
    'menu.grp.newOpen': 'New & Open',
    'menu.grp.save': 'Save',
    'menu.grp.tabs': 'Tabs',
    'menu.grp.export': 'Export',
    'menu.grp.settings': 'Settings',
    'menu.grp.history': 'History',
    'menu.grp.clipboard': 'Clipboard',
    'menu.grp.findOrganize': 'Find & Organize',
    'menu.grp.format': 'Format',
    'menu.grp.selectionExport': 'Selection Export',
    'menu.grp.sidebarSearch': 'Sidebar & Search',
    'menu.grp.fold': 'Fold',
    'menu.grp.mode': 'Mode',
    'menu.grp.inputAssist': 'Input Assists',
    'menu.grp.zoom': 'Zoom',
    'menu.grp.devTheme': 'Dev & Theme',
    'menu.grp.table': 'Table',
    'menu.grp.chartContainer': 'Charts & Containers'
  },
  zh: {
    app: 'VeloxMark',
    services: '服务',
    hide: '隐藏 VeloxMark',
    hideOthers: '隐藏其他',
    unhide: '全部显示',
    quit: '退出 VeloxMark',
    preferences: '偏好设置…',
    file: '文件',
    newFile: '新建',
    openFile: '打开…',
    openFolder: '打开文件夹…',
    quickOpen: '快速打开…',
    openRecent: '打开最近',
    noRecent: '暂无最近文件',
    clearMenu: '清空列表',
    save: '保存',
    saveAs: '另存为…',
    export: '导出',
    pdf: 'PDF…',
    html: 'HTML…',
    close: '关闭',
    closeTab: '关闭标签',
    reopenClosedTab: '重新打开已关标签',
    nextTab: '下一个标签',
    edit: '编辑',
    cut: '剪切',
    copy: '复制',
    paste: '粘贴',
    pasteMatch: '粘贴并匹配样式',
    del: '删除',
    selectAll: '全选',
    copyRichText: '复制为富文本',
    copyAsHtml: '复制为 HTML',
    exportSelectionHtml: '导出选区为 HTML…',
    insertTable: '插入表格…',
    convertToTable: '选区转表格…',
    formatDocument: '格式化文档',
    format: '格式',
    bold: '加粗',
    italic: '斜体',
    inlineCode: '行内代码',
    strikethrough: '删除线',
    highlight: '高亮',
    view: '视图',
    toggleOutline: '切换大纲',
    globalSearch: '文件夹内搜索…',
    focusMode: '专注模式',
    typewriterMode: '打字机模式',
    sourceMode: '源码模式',
    typingAssists: '输入辅助',
    wrapBareUrls: '粘贴时包裹裸链接',
    pasteHtmlMd: '粘贴 HTML 转 Markdown',
    zoomIn: '放大',
    zoomOut: '缩小',
    zoomReset: '重置缩放',
    devTools: '开发者工具',
    toggleTheme: '切换主题',
    insert: '插入',
    insertMermaidDiagram: 'Mermaid 图表…',
    insertCallout: '插入 Callout…',
    window: '窗口',
    minimize: '最小化',
    zoom: '缩放',
    fullscreen: '进入全屏幕',
    front: '前置所有窗口',
    help: '帮助',
    showHelp: 'Markdown 语法参考',
    // ---- menu-tree §3 语义分组名（BE-02，menu:native-parity）----
    // key 与渲染端 i18n menu.grp.* 同名同义（FE-01 同一清单，第 3 份字典独立维护）。
    'menu.grp.newOpen': '新建与打开',
    'menu.grp.save': '保存',
    'menu.grp.tabs': '标签页',
    'menu.grp.export': '导出',
    'menu.grp.settings': '设置',
    'menu.grp.history': '历史',
    'menu.grp.clipboard': '剪贴板',
    'menu.grp.findOrganize': '查找与整理',
    'menu.grp.format': '格式',
    'menu.grp.selectionExport': '选区导出',
    'menu.grp.sidebarSearch': '侧栏与搜索',
    'menu.grp.fold': '折叠',
    'menu.grp.mode': '模式',
    'menu.grp.inputAssist': '输入辅助',
    'menu.grp.zoom': '缩放',
    'menu.grp.devTheme': '开发与主题',
    'menu.grp.table': '表格',
    'menu.grp.chartContainer': '图表与容器'
  }
}
